kind: pipeline
name: default

steps:
- name: frontend
  image: python:3-slim
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - apt-get install -y make
  - pip install -r requirements.txt
  - make test-ci

